name: Postman Test and Allure Report
on:
  push:
    branches:
      - draft-vendor
  schedule:
    - cron: '0 18 * * 4' # Runs every Wednesday by 4pm
    - cron: '0 18 * * 5' # Runs every Friday by 4pm
    - cron: '0 20 * * 0' # Runs every Sunday by 4pm
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install newman and newman-reporter-allure
        run: |
          npm install -g newman newman-reporter-allure
          echo "Newman and newman-reporter-allure installed."

      - name: Run Postman tests
        if: always()
        continue-on-error: true
        run: |
           newman run Postman-Collections/Postman-Collections.json --reporters cli,allure
           echo "Postman tests run."

      - name: Configure Git user
        run: |
          git config --global user.email "github-actions@example.com"
          git config --global user.name "GitHub Actions"

      - name: Create gh-pages branch
        run: |
          # Remove all files from the current branch
          git rm -rf * || true
          # Remove all directories from the current branch
          rm -rf * || true
          # Create a new orphan gh-pages branch
          git checkout --orphan gh-pages
          # Create the vendor directory
          mkdir vendor
          # Add the vendor directory to git
          git add vendor
          # Commit the changes
          git commit -m "Create gh-pages branch with vendor folder"

      - name: Allure report action
        id: build
        uses: simple-elf/allure-report-action@master
        if: always()
        continue-on-error: true
        with:
          allure_results: allure-results
          gh_pages: vendor
          allure_report: allure-report

      # ... (rest of the workflow remains the same)
